### ISSUE TITLE
Readd integration for Forestry 3.6 (disabled by default)

### ISSUE THREAD

**Issue by Beelzaboss** [Tonius/NEI-Integration#100]
Hi there,

I updated to the latest version of NEI Integration today to fix the new Pam Harvest compatibility... But now none of Forestry recipes is showing anymore (Electron Recipes). I also can't update forestry just yet as the .new API is not working with ExtraTrees & ExtraBees mod.

Or is this a bug that doesn't even affect the versions, could this be looked at please?

I am currently using Forestry 3.6.24

Regards,
Beelzaboss

**Comment by canilsen** [comment]
Can confirm. Same issue

**Comment by canilsen** [comment]
Forestry support was removed because 4.0 got its own nei integration. But a lot still uses 3.6 because of binnie mods.

Could the devs please add 3.6 support back in? Even set to false as default in config would be great, so us with 3.6 can enable it.
