### ISSUE TITLE
Bee Stuff

### ISSUE THREAD

**Issue by Zsashas** [Tonius/NEI-Integration#102]
Forestry 4 may have it's own NEI stuff, but that doesn't include showing bee combinations, or even bee products (possibly the more important one).

**Comment by Tonius** [comment]
NEI Integration never added bee breeding recipe handlers. You are probably looking for [NEI Addons](https://bdew.net/neiaddons/), which is not maintained by me. 

NEI Addons still has its own Forestry handlers instead of them being merged into Forestry.

**Comment by Zsashas** [comment]
I thought that NEI Integration was the replacement for NEI Addons?

**Comment by Tonius** [comment]
NEI Integration is the replacement for NEI Plugins, which is an older abandoned mod. NEI Addons is still alive and is a separate mod with its own handlers.
