### ISSUE TITLE
[Suggestion]IC2 UU-Matter Replicator Recipes

### ISSUE THREAD

**Issue by Xee1** [Tonius/NEI-Integration#29]

**Comment by Tonius** [comment]
I'm sorry, but I will refuse to add any handlers for IC2e, for personal reasons. I won't blame you for wanting better NEI support for it, though.

IC2e has a bunch of inbuilt NEI handlers already, so I'm sure they can add them for the other recipe types. They are free to look at my code for help. I won't try to sue them for it :)

**Comment by Xee1** [comment]
No problem @Tonius ! And thanks for the reply, It's just for improve NEI support for the mods, to have a help, also because now wikis are very old! And because ic2 it's a mod with few NEI handlers.
