### ISSUE TITLE
[Suggestion] Hide NEI SPAM

### ISSUE THREAD

**Issue by leSamo** [Tonius/NEI-Integration#39]
Hey, I have an idea for you. A config option for NEI integration to hide some unnecesary stuff from NEI (microblocks, blocks from chisel, crafting recipes for all dyes etc.) or maybe make separate mod for that.

**Comment by Tonius** [comment]
Sounds like what you want is [INpureCore](http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/2196459-1-7-10-inpure-projects-denoflions-mods). It contains most of the stuff you're asking for here, plus a feature to hide stuff you specify it to.

**Comment by leSamo** [comment]
Thanks
