### ISSUE TITLE
NPE: updating screen events

### ISSUE THREAD

**Issue by Sailren** [Tonius/NEI-Integration#40]
this crash happened, when i tried to lookup the recipe for a large eletric engine from buildcraft utilities mod: http://paste.ubuntu.com/9660649/

**Comment by iTitus** [comment]
With the newest versions of IC2 experimental, Buildcraft, Buildcraft Utilities, NEI Integration and their dependencies I do not get this crash.
Can you please give us a mod list with versions?

**Comment by Sailren** [comment]
i used a minetweaker script to change the rolling machine recipes

**Comment by iTitus** [comment]
That could be the issue, maybe the scripts were wrong?
But a null-check would not be bad there.

**Comment by Sailren** [comment]
i used the script from this guy: https://github.com/Dream-Master/Mods-Get-Gregged

in this case the rolling machine thingy

**Comment by iTitus** [comment]
Nein, das ist @Tonius , aber ich hatte zufällig gerade eine Entwicklungumgebung mit dem Quellcode und habe das dann getestet.

**Comment by Sailren** [comment]
kannste das nachvollziehen, was dort geschah? ein problem zwischen minetweaker, railcraft und nei integration

**Comment by iTitus** [comment]
I cannot see what exactly the cause is, there is a null-recipe in the the list which should not be there. Theoretically this should not happen.

**Comment by iTitus** [comment]
Maybe a weird cross-mod interaction.  We really need these damned null-checks everywhere ^^

**Comment by retep998** [comment]
It's really too bad Java went with the design decision of letting anything be null.

**Comment by Tonius** [comment]
I'll just add even more null checks. Though you'd think you can trust other mods not to add broken recipes..

**Comment by iTitus** [comment]
Yeah 0.o
