### ISSUE TITLE
[Suggestion] Thermal Expansion support

### ISSUE THREAD

**Issue by Morpheusblog** [Tonius/NEI-Integration#47]
Support for Thermal Expansion machines like induction smelter, pulverizer, ecc. would be beautiful

**Comment by retep998** [comment]
Those are actually Thermal Expansion machines, and that mod already has NEI handlers for those machines.

**Comment by Tonius** [comment]
Yup, TE already has NEI handlers itself. Do they not work for you or something?

**Comment by Morpheusblog** [comment]
oh sorry, they was not enabled.
