### ISSUE TITLE
Wrong values for Melting Agents in Thermionic Fabricator

### ISSUE THREAD

**Issue by Yulife** [Tonius/NEI-Integration#50]
If you let Glass, Sand and Glass Panes cycle through your NEI they will always show an output for Molten Glass of 500mB. However, Glass & Sand give 1000mB and Glass Panes give 375mB of Molten Glass.

**Comment by Tonius** [comment]
That isn't actually the amount of liquid glass that the input gives, but rather the amount of liquid glass that the recipe uses.

I will try to add a tooltip on the melting inputs though.
