### ISSUE TITLE
BC 6.2.6

### ISSUE THREAD

**Issue by Manuepolis23** [Tonius/NEI-Integration#51]
Can you add again BuildCraft handlers  in the newer versions of NEI -Intergration for those who didn't update to BC 6.3 ?

**Comment by Tonius** [comment]
I assume this is related to Logistics Pipes (correct me if I'm wrong). That mod has updated by now though. Anything else keeping you from updating BC?

**Comment by karelmikie3** [comment]
LP has been updated to buildcraft 6.3

**Comment by Manuepolis23** [comment]
no no .is ok now.thanks anyways
