### ISSUE TITLE
Buildcraft Assembly Table recipes not shown

### ISSUE THREAD

**Issue by Camp12** [Tonius/NEI-Integration#54]
MC - 1.7.10
Buildcraft - 6.3.4
Not Enough Items - 1.7.10-1.0.4.83
NEI Integration - 1.0.5

I can't seem to get NEI to display the recipes for the assembly table. I have tried updating everything and downgrading, but I still am not able to get them to show. Just let me know if there is any useful information that I did not mention.

**Comment by Xee1** [comment]
You need buildcraft compat for BC6.3.X, read the changelog of neiintegration
You can find Buildcraft Compat on buildcraft site

**Comment by Camp12** [comment]
oh I guess I missed that. Thanks for the help :)
