### ISSUE TITLE
Dump option for Crafting Guide (http://crafting-guide.com)

### ISSUE THREAD

**Issue by andrewminer** [Tonius/NEI-Integration#55]
I've recently been working on a website which computes all the raw materials and even step-by-step instructions for making even the most complicated items (how about a full [QuantumSuit](http://crafting-guide.com/crafting/quantumsuit_bodyarmor:quantumsuit_boots:quantumsuit_helmet:quantumsuit_leggings) from IC2?).

I've noticed that this mod adds some options to the data dumps NEI produces, and I was hoping you might add support for [the format](https://github.com/andrewminer/crafting-guide/wiki/Mod-Version-Data-Format) Crafting Guide requires.

Unfortunately, I don't know much about Minecraft modding myself, so I was wondering if you'd consider extending your mod to spit out data in the format Crafting Guide uses?  It would be a huge help!

Thanks!

**Comment by Tonius** [comment]
Sadly, this would require a lot of code for fetching all the different kinds of data from Minecraft and all the different mods, as most of the info is scattered around a lot. I just don't think it's really worth putting in NEI Integration; it'd be more suitable for a separate mod. Sorry!

**Comment by retep998** [comment]
For the record MineTweaker lets you dump a list of all the recipes.
