### ISSUE TITLE
"Updating Screen Events" Crash

### ISSUE THREAD

**Issue by mr10movie** [Tonius/NEI-Integration#56]
I was clicking on random objects in NEI, and then I crashed. http://pastebin.com/UUDtcuYL. Clicking on other similar objects seemed to replicate the crash (GT storage blocks from 6.0)

**Comment by Tonius** [comment]
If you are using the latest version, it would seem that some mod is registering _null_ recipes in the Rolling Machine. In this case, that mod is at fault; NEI Integration probably wouldn't be the only thing to break if some recipes are _null_.

It's pretty hard to track down which mod is causing this, though. Of course, I could also just add _even more_ null checks...

**Comment by retep998** [comment]
You're using a language where anything can be null and nobody even tries to enforce any level of sanity. You can never have enough null checks!

**Comment by mr10movie** [comment]
Yeah, definitely using the latest version.
