### ISSUE TITLE
Console spam , and not working with newest MFR

### ISSUE THREAD

**Issue by crunkazcanbe** [Tonius/NEI-Integration#57]
As the title says 

http://pastebin.com/tgeC5VAS

Thank you!

-Crunk

**Comment by Tonius** [comment]
What versions of CoFH Core and MFR are you using? From the log it seems like you are using versions of them that are incompatible with each other.

**Comment by crunkazcanbe** [comment]
It is all the latest DEV versions as of right now on curse.

**Comment by Tonius** [comment]
This isn't a bug in NEI Integration. It's that the alpha version of MFR didn't adapt to a change in the alpha version of CoFH Core.
You really shouldn't be using the alphas unless you like having stuff break routinely.

**Comment by ultrasn0w** [comment]
Tonius, the new Version of CoFH Core and MFR are now released and no longer in alpha stage.
Would be nice if you can update soon :)

**Comment by Tonius** [comment]
What is there to update? As I said, the crash in this issue was caused by an interaction between alpha versions of MFR and CoFH Core. NEI Integration isn't responsible for that.

**Comment by crunkazcanbe** [comment]
Well when I click to create a new world And get tossed into the new world with this mod installed the menu is up right when starting you know the menu u see when hitting ESC button in game , and when I click back to game I am kicked out of the game and put in the multiplayer menu . WTF un installing this mod stopped that totally .

**Comment by OronDF343** [comment]
This happens with the newest **stable** versions of MFR and CoFHCore 
(MFR RC6-5, CoFHCore RC1-181)
