### ISSUE TITLE
NEI Handler Request

### ISSUE THREAD

**Issue by SkullyGamingMC** [Tonius/NEI-Integration#59]
Hello! I was wondering if it was possible for you to add NEI handlers for the following crafting systems:
-Sewing Machine (Necromancy):
It would be extremely helpful to be able to view the Sewing recipes to create corpse limbs from Necromancy. :)

-Clockwork Assembly Table (Clockwork Phase):
This isn't really necessary, but it would be useful for noobs to the new Clockwork Phase mod.

-Energy Collector (ProjectE):
It would be useful to be able to see what 'fuels' can be made by using the Energy Collector upgrading feature.

-Soul Forge (Soul Shards: The Old Ways):
The Soul Forge is used to make Soul Shards and Soulium... and since they're the main items of the mod it would be extremely useful.

I hope you consider all of these, and it will greatly benefit me and most likely many others who use your wonderful NEI addon! :D

**Comment by Tonius** [comment]
Moved into #48
