### ISSUE TITLE
Request for CustomNPC's Carpentry Bench Support

### ISSUE THREAD

**Issue by Razorskills** [Tonius/NEI-Integration#64]
Please?

http://minecraft.curseforge.com/mc-mods/221826-custom-npcs

If you place a Carpentry Bench, it has its own recipes display, it just doesn't work with NEI. I Wonder if it would be possible to have NEI Link to them, Idk how you do your stuff though.

Although there is a ingame way of making recipes for items with the carpentry bench, might have to be an inside job via mod author: Noppes

**Comment by Brycey92** [comment]
I also think this would be an awesome feature!

**Comment by Tonius** [comment]
Moved into #48
