### ISSUE TITLE
A request for Some NEI help

### ISSUE THREAD

**Issue by CorvusUrro** [Tonius/NEI-Integration#65]
Hello I am one of the developers of Soul Shards: The Old Ways, 
None of our developers have any experience with NEI Handlers, so can I request some assistance in this matter, either helping us get it in our mod, putting it in your mod, or teaching us.
Link: https://github.com/SgtPunishment/Soul-Shards-The-Old-Ways

**Comment by Tonius** [comment]
It's already on my todo list, though I'm not sure when I can get it done. See #48

**Comment by Timeslice42** [comment]
You may want to consider checking out EE3's NEI handlers, since it's open source.
