### ISSUE TITLE
Crash when viewing a Forestry-related recipe

### ISSUE THREAD

**Issue by Pyeroh** [Tonius/NEI-Integration#68]
When I try to see a recipe related to Forestry, the game crashes : http://pastebin.com/yyXqv83P
NEIIntegration 1.0.8
Forestry 3.5.3.11.

I didn't test to rollback Forestry version yet, but I will.

EDIT : tested without Forestry and any of its add-ons, NEI works again as intended

**Comment by Tonius** [comment]
Try the new version 1.0.9. I can't reproduce the issue myself, but you can check if that version fixes it.

**Comment by Pyeroh** [comment]
It fixes it, indeed ! Thanks a lot for your amazing work :D
