### ISSUE TITLE
Ore dictionary tooltip doesn't update after removing an ore dictionary with minetweaker

### ISSUE THREAD

**Issue by Xen1290** [Tonius/NEI-Integration#71]
Hi @Tonius , for example If I remove "nuggetIron" from Iron OreBerry(TConstruct) with minetweaker and I reload the minetweaker scripts, the tooltip doesn't update, and remain.
I hope you understand.
NEIIntegration-MC1.7.10-1.0.9
MineTweaker3-1.7.10-3.0.9C

**Comment by Xee1** [comment]
Fixed, I needed to restart the client, /mt reload is not enough.

**Comment by retep998** [comment]
It would be nice if ore dictionary entries could be removed without restarting the client though

**Comment by Xee1** [comment]
Yeah, I reopen this for visibility.

**Comment by Tonius** [comment]
NEI Integration simply query the oredict every time a tooltip is requested: https://github.com/Tonius/NEI-Integration/blob/master/src/main/java/tonius/neiintegration/mods/mcforge/MCForgeTooltipHandler.java#L42

So I am not sure how to fix this, or if this even mine to fix at all. Seems to be related more to how the oredict itself works, or maybe MineTweaker.

**Comment by retep998** [comment]
Oh, I must've confused this repo with the MineTweaker repo then. Sorry.
