### ISSUE TITLE
Forestry Crash

### ISSUE THREAD

**Issue by S0llux** [Tonius/NEI-Integration#76]
http://pastebin.com/SN8TDyRM

Only Forestry and nei integration installed. Crashes on startup.

Woah i'm stupid this is a duplicate. Curse launcher doesnt install betas by default.

**Comment by XxCoolGamesxX** [comment]
It you look the error say "java.lang.NoClassDefFoundError: codechicken".

You need to install the CodeChicken Core and NotEnoughItems to make it work. :P

**Comment by S0llux** [comment]
I had it installed but i'll test anyways again soon

**Comment by S0llux** [comment]
Closed because i'm stupid. If i find a legit bug I'll make another report
