### ISSUE TITLE
Crash on recipe lookup with Forestry 4.0.0

### ISSUE THREAD

**Issue by bakaxyf** [Tonius/NEI-Integration#84]
[crash report and log](https://gist.github.com/bakaxyf/51de9d7b4a0adfee2b67)
Used:
NEIIntegration-MC1.7.10-1.0.11
forestry_1.7.10-4.0.0.653-unstable

and still happen with build 03ca427f3a9d689380e4c3f161e3f1e3f2f64168
[crash report and log](https://gist.github.com/bakaxyf/0ceb684c2cdef7a6543f)

**Comment by Tonius** [comment]
This is getting quite ridiculous. I'd love for the Forestry devs (paging @mezz) to reconsider integrating NEI support with Forestry. That way, everything wouldn't have to break at every minor change made to the recipe code.

I'll probably add a way to disable different integrations in the mod so that it doesn't break as a whole.

**Comment by MauveCloud** [comment]
This isn't unique to the Forestry 4.0.0 "unstable" builds.  I saw a similar crash with Forestry 3.6.3.20.

**Comment by Tonius** [comment]
Unlikely. I checked the code for 3.6.3.20 and the change that would cause this crash isn't in that version yet. By all means correct me if I'm wrong, but I'm going to need to see a crash log.

**Comment by MauveCloud** [comment]
Sorry, I had somehow failed to notice that I was still using an old version - The similar-looking stack trace I got was using NEI integration 1.0.7 and Forestry 3.6.3.20, but NEI integration 1.0.12 is okay.

**Comment by mezz** [comment]
From a maintainability point of view, it makes the most sense to have this integrated with Forestry. NEI is not being changed, all breaking issues are coming from Forestry. The recipe changes I'm making are tiny, so having NEI Integration included wouldn't really add to the maintenance load at all.

The main issue is that ChickenCode(tm) as a dependency in the dev environment has been a real pain. I'm willing to get over that if you can help set it up. The main holdout for NEI integration has been @CovertJaguar but I think he's been less focused on Forestry lately.

**Comment by Protheus** [comment]
Here is my crash details: http://pastebin.com/2miqsbgn

- NEIIntegration-MC1.7.10-1.0.12
- forestry_1.7.10-4.0.0.679-unstable

**Comment by Xen1290** [comment]
@Protheus disable forestry integration on neiintegration configs, now Forestry NEI Handlers are included in Forestry.

**Comment by Protheus** [comment]
Ahh sweet thank you for the fix

**Comment by mezz** [comment]
@Tonius can you detect when Forestry version is 4.0+ and disable the NEI Handler?
Here's the code I wrote to check Mod version numbers: 
https://github.com/ForestryMC/ForestryMC/blob/dev/src/main/java/forestry/core/proxy/ProxyCommon.java#L280-L298
