### ISSUE TITLE
Presser handler is incompatible as of HarvestCraft 1.7.10-La

### ISSUE THREAD

**Issue by Calenria** [Tonius/NEI-Integration#94]
[Crash Report](https://gist.github.com/Calenria/11c4f394611a02a722f7)

Versions:
* Pam's HarvestCraft 1.7.10La.jar
* NotEnoughItems-1.7.10-1.0.5.118-universal.jar
* forge-1.7.10-10.13.4.1566

**Comment by Tonius** [comment]
Looks like the Presser recipe format changed in HarvestCraft, so NEI Integration no longer recognizes it.

For now, you can disable the HarvestCraft handlers in NEI Integration's config file.

**Comment by Tedyhere** [comment]
Was just about to post this myself.  Thanks for the headsup in the config

**Comment by Gayanfalor** [comment]
Hello guys, should it works if we keep on harvestcraft integration but using an older version of pam's harvestcraft wich has not the changed presser handler ? because i need to see the recipe of seeds ^^

**Comment by Tonius** [comment]
HarvestCraft versions older than 1.7.10La should work fine with the currently released version of NEI Integration.
