### ISSUE TITLE
Feature Request: Two new dump types

### ISSUE THREAD

**Issue by PitchBright** [Tonius/NEI-Integration#95]
Tonius, would it be easy enough for you to bang out two new types of dumps? It'd be awesome if we could dump Foods and also Drinkables (not just potions, but anything that can be drunk). 

That'd make it super easy for people to access food/drink ids&names for when they want to config their stuff for various hunger overhauling or hydration systems provided by other mods.

Thanks man!

**Comment by Tonius** [comment]
Sadly, there is no official registry for me to read from when it comes to food hunger values and whether consumable items are food or drinks. 

However, a simple dump type that just lists items that are consumable is easy to make. Probably not what you're looking for, though :(

**Comment by PitchBright** [comment]
Ah bummer. Yeah, that's what I ended up doing. 700 food items alone   :`(

Either way, thanks for considering it, and responding!
