### ISSUE TITLE
Error when logging into world

### ISSUE THREAD

**Issue by ajthemacboy** [Tonius/NEI-Integration#96]
Here's the issue on NEI addons: https://github.com/bdew/neiaddons/issues/54#issuecomment-161328859

I can't say which mod is causing the error and kicking me to menu, but it appears to be an issue with Forestry 4.2 in both mods.

**Comment by Tonius** [comment]
Both NEI Addons and NEI Integration are causing errors here. Updating NEI Integration should fix my error (my Forestry support was moved into Forestry itself).
