### ISSUE TITLE
Crash with NEIIntegration 1.1.0

### ISSUE THREAD

**Issue by king05** [Tonius/NEI-Integration#99]
Hi I got this Crash wehn I updated NEIIntegration to the newest Version:

http://pastebin.com/i7aUtuvY
and Here also is the OpenEye Version: 

http://openeye.openmods.info/crashes/0398131686ee2f7b4ff2e0fe50cd8343

Hope you can help me. :)

**Comment by Xen1290** [comment]
Update harvestcraft to latest version, this should fix the issue.

**Comment by Tonius** [comment]
NEI Integration 1.1.0 and up only works with HarvestCraft 1.7.10La and up. Either update HarvestCraft or disable HarvestCraft support in NEI Integration's config file.

I really wanted to add a check for this in the mod, but HarvestCraft isn't set to be the right version internally, so the check would be useless.
